### PR TITLE
Fixed API issues

### LINKED ISSUE #19: Prepend /api/ to all API routes
We should prepend /api/ to all of our API's routes so that there's less confusion with which routes are part of the front end and which ones are from the back end.

This should be done when there are few open PRs to avoid unnecessary conflicts and changes required.

e.g. `/auth/login` becomes `/api/auth/login` etc.

### LINKED ISSUE #21: Don't return internal errors on 500 response message.
There are a few places in the API where when some unexpected error occurs (mostly during catch()), we return a 500 error with the exception as the response's message.

This should change and the user should receive an empty response since the code **500** is already indicative of an error on our side that they have no control over.

### LINKED ISSUE #26: Don't log requests for public/static files
Currently, **morgan** is logging all incoming requests to the server. This is causing some spam especially during the initial connection, since the user will load all required images and icons.

It would be great if we can limit logging only for our API endpoints!

### LINKED ISSUE #28: Check if required fields exist in login/signup requests
Currently, we assume that an authentication request will have the required fields (email + password).
However, if the user doesn't send those then we'll return a 500 error because of an exception in the hashing algorithm.

We should address this by checking if all expected fields are actually populated before starting with anything else. This is also a good chance to make sure that we don't return any error messages when we have a 500 status code.

### PR DESCRIPTION
**Pull request by chriskrez**
### Required fields
In some endpoints (`/auth/login`, `/auth/signup` and `contact/submit`) check for required fields was missing. We, now, check if the required fields are missing and address the right error.
Merging this will close #28.

Also, we don't return any error messages when we have a 500 status code.
Merging this will close #21. 

### Skip unwanted logging
Before this PR, morgan was logging all incoming requests to the server. A `skip function` was added to the logger to prevent logging requests during the initial connection.
Merging this we also close #26.

Also, all the API routes are not prepended with `/api/` so that there's less confusion with which routes are part of the front end and which ones are from the back end. This closes #19, too.

### CODE REVIEW

File: src/api/controllers/ContactFormController.js [hunk 1]
```diff
@@ -6,24 +6,47 @@ module.exports = {
...
+      .catch((err) => {
         if (err.errors.email) {
           if (err.errors.email.kind === "regexp") {
-            res.status(500).json({ error: "Invalid email address" });
+            return res.status(400).json({ error: "Invalid email address" });
+          } else if (err.errors.email.kind === "required") {
+            return res.status(400).json({ error: "Field `email` is required" });
           }
-          res.status(500).json(err);
+          return res.status(500).json(err);
```
Comment (din0s) [inline src/api/controllers/ContactFormController.js:24]: Don't return the error here.
```suggestion
          return res.status(500).json();
```

File: src/api/controllers/ContactFormController.js [hunk 2]
```diff
@@ -6,24 +6,47 @@ module.exports = {
...
+        } else if (err.errors.firstName) {
+          if (err.errors.firstName.kind === "required") {
+            return res
+              .status(400)
+              .json({ error: "Field `firstName` is required" });
+          }
+          return res.status(500).json(err);
```
Comment (din0s) [inline src/api/controllers/ContactFormController.js:31]:
```suggestion
          return res.status(500).json();
```

File: src/api/controllers/ContactFormController.js [hunk 3]
```diff
@@ -6,24 +6,47 @@ module.exports = {
...
+        } else if (err.errors.lastName) {
+          if (err.errors.lastName.kind === "required") {
+            return res
+              .status(400)
+              .json({ error: "Field `lastName` is required" });
+          }
+          return res.status(500).json(err);
```
Comment (din0s) [inline src/api/controllers/ContactFormController.js:38]:
```suggestion
          return res.status(500).json();
```

File: src/api/controllers/ContactFormController.js [hunk 4]
```diff
@@ -6,24 +6,47 @@ module.exports = {
...
+        } else if (err.errors.message) {
+          if (err.errors.message.kind === "required") {
+            return res
+              .status(400)
+              .json({ error: "Field `message` is required" });
+          }
+          return res.status(500).json(err);
```
Comment (din0s) [inline src/api/controllers/ContactFormController.js:45]:
```suggestion
          return res.status(500).json();
```

File: src/api/controllers/ContactFormController.js [hunk 5]
```diff
@@ -6,24 +6,47 @@ module.exports = {
...
         } else {
           console.error(`Error during contactForm save():\n${err}`);
-          res.status(500).json(err);
+          return res.status(500).json(err);
```
Comment (din0s) [inline src/api/controllers/ContactFormController.js:48]:
```suggestion
          return res.status(500).json();
```
